### ISSUE TITLE
Infinite loop in binary_fuse8_populate()

### ISSUE THREAD

**Issue by jamescooper-blis** [FastFilter/FilterPassword#7] opened 2022-03-16 16:05 UTC
Hi, while experimenting with lib I've seemingly run into an infinite loop coming from here:

```
      while (reverseOrder[startPos[segment_index]] != 0) {
        segment_index++;
        segment_index &= maskblock;
      }
```

I detect it by adding the following:

```
      uint64_t checkIndex = segment_index;
      while (reverseOrder[startPos[segment_index]] != 0) {
        segment_index++;
        if (segment_index == checkIndex) {
            printf("Infinite loop\n");
        }
        segment_index &= maskblock;
      }
```
I've made sure the duplicates are removed. Is this a 'game-over' scenario?
It happens in the second iteration of `for (int loop = 0; true; ++loop)`

**Comment by lemire** [comment] 2022-03-16 16:12
You may have identified a bug. Please provide a reproducible test case and I will investigate.

It should not happen.

**Comment by jamescooper-blis** [comment] 2022-03-16 16:54
That's difficult to do. But from hacking around it seems that the `reverseOrder` array doesn't get zeroed when this path is taken: https://github.com/FastFilter/FilterPassword/blob/6202ea395356a6af7c831020d6e73ae5581f5277/dependencies/xor_singleheader/include/binaryfusefilter.h#L279

I assume everything else needs to be reset too. I'd raise a PR but I've hacked around the code a fair bit.

**Comment by lemire** [comment] 2022-03-16 20:29
Yep. Since it is a very rare occurence, it may very well be the case that it is a bug.

**Comment by lemire** [comment] 2022-03-23 15:28
I have updated the code according to your analysis. Since we do not have a test case, I cannot verify. Closing. Please reopen if needed.

**Closed as completed by lemire** 2022-03-23 15:28 UTC
