### ISSUE TITLE
Bloom filter false negatives on full HIBP list (upstream bug)

### ISSUE THREAD

**Issue by solardiz** [FastFilter/FilterPassword#2] opened 2020-01-17 18:14 UTC
The `bloom12` filter here produces false negatives when built from the full `pwned-passwords-sha1-ordered-by-hash-v5.txt`, whereas the `xor8` filter appears to work. I suspect the reason why is that a Bloom filter this large needs larger than 32-bit bit indices, whereas the Xor filter gets away by indexing byte triplets instead (it'd probably similarly fail at even larger input lists). I didn't investigate this for real, but I think my guess is corroborated by the `bloom12` filter being suspiciously compressible, which for a size-optimal Bloom filter suggests the bit sets are distributed non-uniformly:

```
$ ls -l bloom12.bin 
-rw-------. 1 solar solar 832918016 Jan 17 18:59 bloom12.bin
$ gzip -1c bloom12.bin | wc -c
470833967
```

**Comment by lemire** [comment] 2020-01-17 20:09
The false positive was a mistake on my part.

I would not expect the resulting bloom filter data to be compressible given our choice of K. 

But, of course, the xor filter *is* compressible.

cc @thomasmueller

**Comment by lemire** [comment] 2020-01-17 20:10
I am going to close this given the fixes that I just checked in. If you can reproduce the false negatives, please re-open. If you can verify that the Bloom filters are compressible, please open an issue as well.

**Comment by solardiz** [comment] 2020-01-17 21:20
Thanks. Using the new code, no false negatives for e.g. 100M input lines, but with the full ~550M lines there are:

```
$ ./build_filter -V -o bloom12.bin -f bloom12 pwned-passwords-sha1-ordered-by-hash-v5.txt
I read 555278657 hashes in total (51.530 seconds).
Bytes read = 24470276290.
Constructing the filter...
Done in 82.450 seconds.
Checking for false negatives
Detected a false negative. You probably have a bug. Aborting.
```

**Comment by solardiz** [comment] 2020-01-17 21:27
Looking at the code confirms my initial guess: the `a` input to `data[reduce(a, this->arrayLength)] |= getBit(a);` (and the corresponding lookup) is 32-bit, and that's just not enough for a filter of this size.

The filter being compressible is another aspect of this same issue, so I won't open another one.

**Comment by solardiz** [comment] 2020-01-17 21:33
BTW, I initially made this guess without even looking at the code because I had been thinking of what filter type to choose for my own application (I want to add this functionality to passwdqc 2.0) and realized I'd run into this limitation with Bloom filters if I use your `reduce` trick (thank you for blogging about it!) yet don't require compiler support for larger than 64-bit integers (nor implement those on my own). So I'd need to either use powers of 2 for the Bloom filter size (where I can mask the needed number of bits) or use a variation of cuckoo or xor filters.

**Comment by lemire** [comment] 2020-01-17 21:48
I have pushed the bug upstream
https://github.com/FastFilter/fastfilter_cpp/issues/7

There is a problem.




> yet don't require compiler support for larger than 64-bit integers (nor implement those on my own)

I am not sure which compiler you are using, but we have a portable implementation (works with Visual Studio, GNU GCC, clang) at https://github.com/lemire/fastrange

**Comment by lemire** [comment] 2020-01-17 22:05
Thank you for your report. There was yet one more bug, this time upstream. The issue is with the "AddAll" function. It suffers from an overflow. I have simply worked around it and I call repeatedly the "Add" function. Not as fast, but safer.

I am closing this issue, reopen if other problems emerge.

**Closed as completed by lemire** 2020-01-17 22:05 UTC

**Comment by lemire** [comment] 2020-01-17 22:14
> a input to data[reduce(a, this->arrayLength)] |= getBit(a); (and the corresponding lookup) is 32-bit, and that's just not enough for a filter of this size.

I don't think it is the correct diagnostic. Of course, the output of reduce is a 32-bit integer, but it is an index in a 64-bit array. So you can index 32 GB of data. If you have a Bloom filter that exceeds 32 GB, you have *other* problems.

The problem is indeed an overflow issue, but one that has to do with a buffering technique we use in the AddAll function, as an optimization.

**Comment by solardiz** [comment] 2020-01-18 14:01
You seem to be partially correct:

Yes, the problem causing false negatives was different, and you seem to have just fixed it. Thanks!

However, that line I quoted (and its counterpart on lookup) is also problematic. Even though the array indexing is OK for up to 32 GiB, the information being used as array index and as bit index is redundant and the set of possible values of `a` is insufficient to use a Bloom filter larger than 4 gigabits. In fact, I expect that things start being sub-optimal already at smaller sizes (below 4 gigabits) because the information that `reduce` extracts overlaps with what `getBit` extracts (using non-overlapping bitmasks instead of the `reduce` trick would have avoided this issue, but would have required the filter size to be a power of 2). The result is probably a higher than expected false positive rate, and the Bloom filter being compressible. With your latest code:

```
$ ./build_filter -V -o bloom12.bin -f bloom12 pwned-passwords-sha1-ordered-by-hash-v5.txt
I read 555278657 hashes in total (52.480 seconds).
Bytes read = 24470276290.
Constructing the filter...
Done in 54.090 seconds.
Checking for false negatives
Verified with success: no false negatives
filter data saved to bloom12.bin. Total bytes = 832918016. 
$ gzip -1c bloom12.bin | wc -c
697779389
```

I didn't directly test for false positive rate - you might want to add such tests for all filter types. In fact, I'd expect that if you do, you'd probably discover additional issues. ;-)

What other problems would I have with a Bloom filter that exceeds 32 GiB? Do you mean with your code (where only the first 32 GiB would actually be used, as I understand) or in general?

Thank you for the reference to `fastrange`. For my use, the fallback to modulo division in `fastrange64` is inappropriate, because it'd make the compiled filters non-portable between systems... unless I also encode this one bit of information along with the filter and force a particular code path on lookup, but this is more complicated than implementing a widening 64x64 multiplication manually.
